version: "3.7"

#
# 警告 compose 文件中包含中文可能会报错，所以阅读之后请删掉中文
#

#
# docker-compose.yml 文件是为了方便本地测试构建镜像，实际请在 CI 服务器中构建镜像
#
# @link https://docs.docker.com/compose/compose-file/
#
# 避免使用 docker build -t ... 命令
#
#
# $ docker-compose build
#

services:
  #
  # $ docker-compose build test
  #
  # test:
  #  build:
  #    context: .
  #    dockerfile: test.Dockerfile
  #    args:
  #      - PHP_VERSION_72=7.2.13
  #      - PHP_VERSION_71=7.1.25
  #      - PHP_VERSION_70=7.0.33
  #      - PHP_VERSION_56=5.6.39
  #  image: ${DOCKER_HUB_USERNAME:-khs1994}/EXAMPLE

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NGINX_VERSION=${NGINX_VERSION:-1.15.7}
      target: nginx
    image: ${DOCKER_HUB_USERNAME:-khs1994}/nginx:${NGINX_VERSION:-1.15.7}-pro-alpine
    depends_on:
      - php72
      # - php71
      # - php70
      # - php56

  # 项目使用哪个 PHP 版本就保留哪个服务，其他注释
  php72:
    build:
      context: .
      dockerfile: Dockerfile
      target: php
      args:
        - PHP_VERSION=${PHP_VERSION_72:-7.2.13}
        - NODE_VERSION=${NODE_VERSION:-11.4.0}
        - NODE_REGISTRY=https://registry.npm.taobao.org
    image: ${DOCKER_HUB_USERNAME:-khs1994}/php:${PHP_VERSION_72:-7.2.13}-pro-alpine

#  php71:
#    build:
#      context: .
#      dockerfile: Dockerfile
#      target: php
#      args:
#        - PHP_VERSION=${PHP_VERSION_71:-7.1.23}
#    image: ${DOCKER_HUB_USERNAME:-khs1994}/php:${PHP_VERSION_71:-7.1.23}-pro-alpine
#
#  php70:
#    build:
#      context: .
#      dockerfile: Dockerfile
#      target: php
#      args:
#        - PHP_VERSION=${PHP_VERSION_70:-7.0.33}
#    image: ${DOCKER_HUB_USERNAME:-khs1994}/php:${PHP_VERSION_70:-7.0.33}-pro-alpine
#
#  php56:
#    build:
#      context: .
#      dockerfile: Dockerfile
#      target: php
#      args:
#        - PHP_VERSION=${PHP_VERSION_56:5.6.39}
#    image: ${DOCKER_HUB_USERNAME:-khs1994}/php:${PHP_VERSION_56:5.6.39}-pro-alpine
