version: '2'

services:
    gerrit2:
        image: openfrontier/gerrit
        container_name: gerrit
        network_mode: host
        restart: always
        ports:
            - 8080:8080
            - 29418:29418
#        volumes:
#            - gerrit-site:/var/gerrit/review_site
        environment:
            - WEBURL=${WEBURL}
            - HTTPD_LISTENURL=proxy-https://*:8080/
            - SMTP_SERVER=smtp.126.com 
            - SMTP_SERVER_PORT=465 
            - SMTP_USER=docker_lab@126.com 
            - SMTP_PASS=zxcasd123
            - SMTP_ENCRYPTION=ssl 
            - SMTP_CONNECT_TIMEOUT=60sec 
            - SMTP_FROM=docker_lab@126.com

#volumes:
    #gerrit-site:
