kind: Deployment
apiVersion: extensions/v1beta1
metadata:                                             #必选，元数据
  name: string                                        #必选，Pod名称
  namespace: string                                   #必选，Pod所属的命名空间
  labels:                                             #自定义标签
    name: string                                      #自定义标签名字
  annotations:                                        #自定义注释列表
    name: string
spec:
  progressDeadlineSeconds: number                     #用于指定在系统报告“部署失败”进展之前等待部署进度的秒数,如果指定，该字段需要大于.spec.minReadySeconds
  minReadySeconds: number                             #应该准备好的最小秒数
  revisionHistoryLimit: number                        #修订历史记录条数
  replicas: number                                    #重复的pod个数
  strategy:
    type: RollingUpdate|Recreate                      #定义更新方式,RollingUpdate:滚动更新(默认),Recreate:重新创建
    rollingUpdate:
      maxSurge: number%                               #最大溢出数量百分比的值
      maxUnavailable: number%                         #最大不可用数量 百分比
  selector:                                           #应用此deployment的选择器
    matchExpressions:                                 #匹配表达式
    matchLabels:                                      #label匹配方式
      key1: string
  template:                                           #描述deployment中的pod节点模板
    #<节点内容参照pod.yaml>