version: '2'

services:
    jenkins-data:
        image: busybox
        container_name: jenkins-data
        volumes:
            - jenkins_home:/var/jenkins_home
        command: chown -R 1000 /var/jenkins_home 
    
    jenkins:
        build: .
        image: jenkins-docker
        container_name: jenkins
        privileged: true
        user: jenkins
        volumes_from:
            - jenkins-data
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - 8080:8080
            - 50000:50000
        depends_on:
            - jenkins-data

volumes:
    jenkins_home:


