version: '2'

services:
    jenkins-slave:
        build: 
            context: .
            dockerfile: Dockerfile-slave
        image: jenkins-docker-slave
        container_name: jenkins-jnlp-slave
        privileged: true
        user: jenkins
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

        environment:
            - JENKINS_URL=${JENKINS_URL}
        command: ${SECRET} ${SLAVE_NAME}
