version: "3.7"

x-common:
  &default-common
  restart: always
  env_file:
    - ./cli/timezone.env
  networks:
    - backend
  # dns:
  #   - ${DNS:-114.114.114.114}

x-labels:
  &default-labels
  labels:
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}=true

x-build:
  &default-build
  # Dockerfile: my.Dockerfile
  args:
    ALPINE_URL: mirrors.ustc.edu.cn # dl-cdn.alpinelinux.org

x-build-debian:
  &default-build-debian
  # Dockerfile: my.Dockerfile
  args:
    DEB_URL: mirrors.ustc.edu.cn # deb.debian.org
    DEB_SECURITY_URL: mirrors.ustc.edu.cn/debian-security/ # security.debian.org

services:

  # MySQL not in arm
  mariadb:
    << : *default-common
    << : *default-labels
    # build:
    #   << : *default-build-debian
    #   context: ./dockerfile/${ARM_ARCH:-arm64v8}/mysql
    #   dockerfile: Dockerfile
    # image: lnmp-mysql:latest
    image: "${ARM_ARCH:-arm64v8}/mysql:${LNMP_MYSQL_VERSION:-8.0.13}"
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: test
      # MYSQL_USER:
      # MYSQL_PASSWORD:
    ports:
      - "${LNMP_MYSQL_PORT:-127.0.0.1:3306}:3306"
      - "${LNMP_MYSQL_PORT_X:-127.0.0.1:33060}:33060"
    volumes:
      - ./config/mysql/${LNMP_MYSQL_CONF:-docker.cnf}:/etc/mysql/conf.d/docker.cnf:ro
      - ./backup/init:/docker-entrypoint-initdb.d:ro
      - mysql-data:${LNMP_MYSQL_DATA:-/var/lib/mysql}
      - ./log/mysql:/var/log/mysql
      - ./backup/mysql:/backup

  mysql:
    << : *default-common
    image: "${ARM_ARCH:-arm64v8}/mariadb:${LNMP_MARIADB_VERSION:-10.4.0}"
    environment:
      # @link https://github.com/docker-library/docs/tree/master/mariadb#environment-variables
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: test
      # MYSQL_USER:
      # MYSQL_PASSWORD:
    ports:
      - "${LNMP_MYSQL_PORT:-127.0.0.1:3306}:3306"
    volumes:
      - ./config/mariadb/${LNMP_MARIADB_CONF:-docker.cnf}:/etc/mysql/conf.d/docker.cnf:ro
      # @link https://github.com/docker-library/docs/tree/master/mariadb#initializing-a-fresh-instance
      - ./backup/init:/docker-entrypoint-initdb.d:ro
      - mariadb-data:${LNMP_MARIADB_DATA:-/var/lib/mysql}
      - ./log/mariadb:/var/log/mysql
      - ./backup/mariadb:/backup
    command:
      - mysqld
      - --character-set-server=utf8mb4
    secrets:
      - db_root_password

  redis:
    << : *default-common
    << : *default-labels
    # build:
    #   << : *default-build
    #   << : *default-build-debian
    #   context: ./dockerfile/${ARM_ARCH:-arm64v8}/redis/
    #   dockerfile: Dockerfile
    # image: lnmp-redis:latest
    image: "${ARM_ARCH:-arm64v8}/redis:${LNMP_REDIS_VERSION:-5.0.3}${ARM_BASED_OS}"
    volumes:
      - ./config/redis/${LNMP_REDIS_CONF:-redis.conf}:/redis.conf:ro
      - ./log/redis:/var/log/redis
      - redis-data:/data
    ports:
      - "${LNMP_REDIS_PORT:-127.0.0.1:6379}:6379"
    command: [
      "redis-server",
      "/redis.conf",
      "--daemonize no",
      "--logfile /var/log/redis/redis.log",
      "--bind 0.0.0.0"
      ]

  memcached:
    << : *default-common
    << : *default-labels
    # build:
    #   << : *default-build-debian
    #   << : *default-build
    #   context: ./dockerfile/${ARM_ARCH:-arm64v8}/memcached/
    #   dockerfile: Dockerfile
    image: "${ARM_ARCH:-arm64v8}/memcached:${LNMP_MEMCACHED_VERSION:-1.5.12}${ARM_BASED_OS}"
    env_file:
      - ./cli/timezone.env
    volumes:
      - zoneinfo-data:/usr/share/zoneinfo
    ports:
       - "${LNMP_MEMCACHED_PORT:-127.0.0.1:11211}:11211"

  rabbitmq:
    << : *default-common
    << : *default-labels
    # build:
    #   << : *default-build-debian
    #   << : *default-build
    #   context: ./dockerfile/${ARM_ARCH:-arm64v8}/rabbitmq/
    #   dockerfile: Dockerfile
    image: "${ARM_ARCH:-arm64v8}/rabbitmq:${LNMP_RABBITMQ_VERSION:-3.7.8}-management${ARM_BASED_OS}"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - zoneinfo-data:/usr/share/zoneinfo
    env_file:
      - ./cli/timezone.env
    # ports:
    #   - "15672"
    #   - "5672"

  postgresql:
    << : *default-common
    << : *default-labels
    # build:
    #   << : *default-build-debian
    #   << : *default-build
    #   context: ./dockerfile/${ARM_ARCH:-arm64v8}/postgresql/
    #   dockerfile: Dockerfile
    image: "${ARM_ARCH:-arm64v8}/postgres:${LNMP_POSTGRESQL_VERSION:-11.1}${ARM_BASED_OS}"
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_root_password
      - POSTGRES_DB=test
    volumes:
      - postgresql-data:/var/lib/postgresql
      - zoneinfo-data:/usr/share/zoneinfo
    ports:
      - "${LNMP_POSTGRESQL_PORT:-127.0.0.1:5432}:5432"
    secrets:
      # default is mysql password
      - db_root_password

  mongodb:
    << : *default-common
    << : *default-labels
    # build:
    #   << : *default-build-debian
    #   context: ./dockerfile/${ARM_ARCH:-arm64v8}/mongodb/
    #   dockerfile: Dockerfile
    # image: lnmp-mongodb:lastet
    image: ${ARM_ARCH:-arm64v8}/mongo:${LNMP_MONGODB_VERSION:-4.1.5}
    volumes:
      - ./config/mongodb/${LNMP_MONGODB_CONF:-mongod.conf}:/etc/mongod.conf
      - mongodb-data:/data/db
      - ./log/mongodb/mongo.log:/var/log/mongodb/mongo.log
    ports:
      - "${LNMP_MONGODB_PORT:-127.0.0.1:27017}:27017"
    env_file:
      - ./cli/timezone.env
    command: ["mongod","--config","/etc/mongod.conf"]

  php7:
    &php7
    << : *default-common
    << : *default-labels
    # build:
    #   << : *default-build-debian
    #   << : *default-build
    #   context: ./dockerfile/${ARM_ARCH:-arm64v8}/php/
    #   dockerfile: Dockerfile
    # image:lnmp-php:lastet
    image: "khs1994/${ARM_ARCH:-arm64v8}-php:${LNMP_PHP_VERSION:-7.2.13}-fpm-${ARM_PHP_BASED_OS}"
    networks:
      - frontend
      - backend
    volumes:
      - ${APP_ROOT:-./app}:${LNMP_PHP_PATH:-/app}
      - ./config/php/${LNMP_PHP_INI:-php.development.ini}:/usr/local/etc/php/php.ini:ro
      - ./config/php/${LNMP_PHP_XDEBUG_INI:-docker-xdebug.ini}:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini.temp:ro
      - ./config/php/${LNMP_PHP_EXTRA_INI:-docker-php.ini}:/usr/local/etc/php/conf.d/docker-php.ini:ro
      - ./config/php/${LNMP_PHP_FPM_CONF:-zz-docker.conf}:/usr/local/etc/php-fpm.d/zz-docker.conf:ro
      - ./config/php/${LNMP_PHP_FPM_CONF:-zz-docker-log.conf}:/usr/local/etc/php-fpm.d/zz-docker-log.conf:ro
      - ./config/php/${LNMP_PHP_FPM_CONF:-zz-docker-slow-log.conf}:/usr/local/etc/php-fpm.d/zz-docker-slow-log.conf:ro
      - ./config/php/${LNMP_PHP_FPM_CONF:-zz-docker-pm.conf}:/usr/local/etc/php-fpm.d/zz-docker-pm.conf:ro
      - ./log/php:/var/log/php
      - ./log/supervisord:/var/log/supervisord
      - ./log/supervisord.log:/var/log/supervisord.log
      - composer_cache-data:/tmp/cache
      - ./dockerfile/php-fpm/docker-php-entrypoint:/usr/local/bin/docker-php-entrypoint
    environment:
      - LNMP_DOCKER_VERSION=${LNMP_DOCKER_VERSION:-v18.09} ${ARM_ARCH:-arm64v8} With Pull Docker Image
      - APP_ENV=development
      - XDEBUG_REMOTE_HOST=${XDEBUG_REMOTE_HOST:-192.168.199.100}
    command: ["php-fpm","-R"]

  supervisord:
    << : *php7
    networks:
      - backend
    image: "khs1994/${ARM_ARCH:-arm64v8}-php:${LNMP_PHP_VERSION:-7.2.13}-supervisord-alpine"
    secrets:
      - source: supervisord_ini
        target: /etc/supervisor.d/supervisord.ini
    command: ["/usr/bin/supervisord","-n"]
    expose:
      - 9001

  nginx:
    << : *default-common
    << : *default-labels
    # build:
    #   << : *default-build-debian
    #   << : *default-build
    #   context: ./dockerfile/${ARM_ARCH:-arm64v8}/nginx/
    #   dockerfile: Dockerfile
    # image: lnmp-nginx:latest
    image: "${ARM_ARCH:-arm64v8}/nginx:${LNMP_NGINX_VERSION:-1.15.7}"
    networks:
      - frontend
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ${APP_ROOT:-./app}:${LNMP_PHP_PATH:-/app}
      - ./config/${LNMP_NGINX_CONF_D:-nginx}:/etc/nginx/conf.d:ro
      - ./config/etc/nginx/${LNMP_NGINX_CONF:-nginx.conf}:/etc/nginx/nginx.conf:ro
      - ./config/etc/nginx/fastcgi.conf:/etc/nginx/fastcgi.conf:ro
      - ./log/nginx:/var/log/nginx
    depends_on:
      - php7

  httpd:
    << : *default-common
    << : *default-labels
    # build:
    #   << : *default-build-debian
    #   << : *default-build
    #   context: ./dockerfile/${ARM_ARCH:-arm64v8}/httpd
    #   dockerfile: Dockerfile
    # image: lnmp-httpd:latest
    image: "${ARM_ARCH:-arm64v8}/httpd:${LNMP_HTTPD_VERSION:-2.4.37}${ARM_BASED_OS}"
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ${APP_ROOT:-./app}:${LNMP_PHP_PATH:-/app}
      - ./config/etc/httpd/${LNMP_HTTPD_CONF:-httpd.conf}:/usr/local/apache2/conf/httpd.conf
      - ./config/httpd/${LNMP_HTTPD_CONF_D:-conf.d}:/usr/local/apache2/conf.d
      - ./log/httpd:/usr/local/apache2/logs
      - zoneinfo-data:/usr/share/zoneinfo
    working_dir: /app
    networks:
      - frontend
    depends_on:
      - php7

networks:
  frontend:
    << : *default-labels
  backend:
    << : *default-labels

volumes:
  mysql-data:
    << : *default-labels
  mariadb-data:
    << : *default-labels
  redis-data:
    << : *default-labels
  rabbitmq-data:
    << : *default-labels
  postgresql-data:
    << : *default-labels
  mongodb-data:
    << : *default-labels
  zoneinfo-data:
    << : *default-labels
  composer_cache-data:
    external: true
    name: lnmp_composer_cache-data

secrets:
  db_root_password:
    << : *default-labels
    file: ./secrets/${LNMP_DB_ROOT_PASSWORD_PATH:-db_root_password.txt}
  supervisord_ini:
    << : *default-labels
    file: ./config/supervisord/${LNMP_SUPERVISORD_INI_PATH:-supervisord.ini}
