apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole                                                   #资源类型,需要注意的是ClusterRole是集群中的角色,可以跨namespace
                                                                    #如果将role权限限制在一个namespace中,请使用Role
metadata:
  name: ambassador
rules:                                                              #规则
- apiGroups: [""]                                                   #指定api组
  resources:                                                        #资源列表
  - services
  verbs: ["get", "list", "watch"]                                   #可以进行的操作
                                                                    #get,list,watch,create,update,patch,delete