apiVersion: autoscaling/v2alpha1                  #注意版本号
kind: HorizontalPodAutoscaler
metadata:
  name: string                                    #HPA名称
  namespace: string                               #所在的namespace
spec:
  scaleTargetRef:                                 #目标资源
    apiVersion: apps/v1beta1
    kind: Deployment                              #资源的类型
    name: string
  minReplicas: 1                                  #最小缩容
  maxReplicas: 10                                 #最大扩容
  metrics:                                        #定义指标
  - type: Resource                                #指标类型
    resource:
      name: cpu                                   #定义指标中的某一项的名字,例如 cpu,memory等等
      targetAverageUtilization: 50                #默认指标收集时间是1分钟,指定目标平均使用量